name: Build Source Code on Linux üêß

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]


env:
  BINARY_NAME: resin

jobs:
  ubuntu-build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v4
      with:
        # The binary versioning depends to on the git annotated tags. 
        # This line forces checkout action to fetch the tags, see
        # https://github.com/actions/checkout/issues/701.
        fetch-depth: 0

    - name: Install dependencies
      id: install-deps
      run: |
        sudo apt-get update
        sudo apt-get install python3 gcc-14 g++-14 git libwayland-dev libxkbcommon-dev cppcheck xorg-dev cmake cmake-format clangd clang clang-tidy git

    - name: Clang Build
      id: clang-build
      run: |
        cmake --preset=ci-ubuntu-clang
        cmake --build --preset=ci-ubuntu-clang

    - name: Clean up the build directory
      id: clean-up
      run: |
        rm -r build

    - name: GCC Build
      id: gcc-build
      run: |
        cmake --preset=ci-ubuntu-gcc
        cmake --build --preset=ci-ubuntu-gcc
        strip ./build/bin/${{ env.BINARY_NAME }}

    - name: Create artifact 
      id: create-artifact
      run: |
        mkdir artifact
        tar -czf ./artifact/${{ env.BINARY_NAME }}-linux-x86_x64.tar.gz ./build/bin/${{ env.BINARY_NAME }}
    
    - name: Upload artifact 
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BINARY_NAME }}-binary-archives
        path: artifact

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./artifact/${{ env.BINARY_NAME }}-linux-x86_x64.tar.gz

    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
      if: github.event_name != 'pull_request'
      with:
        ref: unstable-latest 

    - name: Pre-Release
      uses: softprops/action-gh-release@v2
      if: github.event_name != 'pull_request'
      with:
        files: ./artifact/${{ env.BINARY_NAME }}-linux-x86_x64.tar.gz
        prerelease: true
        name: Auto Unstable Build
        tag_name: unstable-latest
