name: labeler

on: [pull_request]

jobs:
  labeler:
    permissions:
      pull-requests: write
      contents: read
      issues: write
    runs-on: ubuntu-latest
    name: Label the PR
    env:
      MAJOR_LABEL: 'version/major ðŸ—ï¸'
      MAJOR_PREFIXES: 'release'
      MINOR_LABEL: 'version/minor ðŸ”¨'
      MINOR_PREFIXES: 'feature'
      PATCH_LABEL: 'version/patch ðŸª¶'
      PATCH_PREFIXES: 'bugfix task'
    steps:
      - name: Determine version label
        id: extract-version-label
        run: |
          branch="${{github.head_ref}}"
          prefix=${branch%%/*}
          echo "The PR branch name is: ${{ github.head_ref }}, the prefix is: ${prefix}"

          # Check if prefix matches any version prefix
          if [[ "$MAJOR_PREFIXES" == *"$prefix"* ]]; then
              echo "Found major prefix."
              echo "label=$MAJOR_LABEL" >> $GITHUB_OUTPUT
          elif [[ "$MINOR_PREFIXES" == *"$prefix"* ]]; then
              echo "Found minor prefix."
              label="$MINOR_LABEL"
          elif [[ "$PATCH_PREFIXES" == *"$prefix"* ]]; then
              echo "Found patch prefix."
              label="$PATCH_LABEL"
          else
              echo "No matching prefix found!"
          fi
      # - run: gh issue edit "$NUMBER" --add-label "$LABELS"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GH_REPO: ${{ github.repository }}
      #     NUMBER: ${{ github.event.issue.number }}
      #     LABELS: triage
